version: 3

services:
    # elasticsearch
    elasticsearch:
        image: elasticsearch:7
        container_name: elasticsearch
        restart: always
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
            - ./elasticsearch/logs:/usr/share/elasticsearch/logs
            - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - es_network
    # kibana
    kibana:
        image: kibana:7
        container_name: kibana
        environment:
          - I18N_LOCALE=zh-CN
          - XPACK_GRAPH_ENABLED=true
          - TIMELION_ENABLED=true
          - XPACK_MONITORING_COLLECTION_ENABLED="true"
        ports:
          - "5601:5601"
        depends_on:
            - elasticsearch
        volumes:
            - ./kibana/config:/usr/share/kibana/config #配置文件挂载
        networks:
            - es_network

networks:
    es_network:
        driver: bridge